spring:
  application:
    name: erp-backend
  datasource:
    url: jdbc:postgresql://localhost:5432/uni_manage_school
    username: postgres
    password: manish
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 2126
